name: custom_calendar
description: "My customized calendar based on infinite_calendar_view"
version: 2.5.4+custom

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sticky_infinite_list_plus: ^4.0.2+2
  intl: any